/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/job-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Requests */
        get: operations["list_job_requests_api_job_requests_get"];
        put?: never;
        /**
         * Create Job Request
         * @description Ingest an inbound email and, by default, run the pipeline on it.
         *
         *     The pipeline is synchronous here. For a company receiving a few dozen
         *     requests a day that is the right call: it keeps the request/response model
         *     honest and avoids a queue the deployment does not need yet. A real
         *     production deployment would move this to a worker; that is called out in
         *     the README.
         */
        post: operations["create_job_request_api_job_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-requests/{job_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Request */
        get: operations["get_job_request_api_job_requests__job_request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-requests/{job_request_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Pipeline
         * @description Re-run the pipeline on an existing request, e.g. after a prompt change.
         */
        post: operations["rerun_pipeline_api_job_requests__job_request_id__rerun_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Approval Queue
         * @description Everything a reviewer needs, in one request per screen rather than per card.
         */
        get: operations["approval_queue_api_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_api_quotes__quote_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Quote
         * @description Correct a quote and re-price it. Does not approve it.
         */
        post: operations["edit_quote_api_quotes__quote_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Quote
         * @description Approve and send. The only path in the API that reaches the messaging adapter.
         */
        post: operations["approve_quote_api_quotes__quote_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Quote */
        post: operations["reject_quote_api_quotes__quote_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Without Approval
         * @description Deliberately unimplemented, and documented as such.
         *
         *     A direct send endpoint is the obvious thing for a caller to look for, and
         *     its absence would read as an oversight. It exists, in the schema, and
         *     always refuses — pointing the caller at the approval flow.
         */
        post: operations["send_without_approval_api_quotes__quote_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog */
        get: operations["get_catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Runs */
        get: operations["list_eval_runs_api_evals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Eval Run */
        get: operations["latest_eval_run_api_evals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/{eval_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Run */
        get: operations["get_eval_run_api_evals__eval_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Used by docker-compose healthchecks and the web client.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressOut */
        AddressOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Line1 */
            line1: string;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Travel Zone */
            travel_zone: string;
            /** Property Notes */
            property_notes: string | null;
            /** Is Primary */
            is_primary: boolean;
        };
        /** AgentRunDetail */
        AgentRunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Request Id */
            job_request_id: string | null;
            /** Job Request Subject */
            job_request_subject: string | null;
            status: components["schemas"]["RunStatus"];
            /** Model */
            model: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Total Tokens In */
            total_tokens_in: number;
            /** Total Tokens Out */
            total_tokens_out: number;
            /** Total Cost Microcents */
            total_cost_microcents: number;
            /** Cost Display */
            cost_display: string;
            /** Outcome */
            outcome: string | null;
            /** Error */
            error: string | null;
            /** N Steps */
            n_steps: number;
            /** Steps */
            steps: components["schemas"]["TraceStepOut"][];
        };
        /** AgentRunSummary */
        AgentRunSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Request Id */
            job_request_id: string | null;
            /** Job Request Subject */
            job_request_subject: string | null;
            status: components["schemas"]["RunStatus"];
            /** Model */
            model: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Total Tokens In */
            total_tokens_in: number;
            /** Total Tokens Out */
            total_tokens_out: number;
            /** Total Cost Microcents */
            total_cost_microcents: number;
            /** Cost Display */
            cost_display: string;
            /** Outcome */
            outcome: string | null;
            /** Error */
            error: string | null;
            /** N Steps */
            n_steps: number;
        };
        /** AppliedRuleOut */
        AppliedRuleOut: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            delta: components["schemas"]["Money"];
        };
        /**
         * ApprovalAction
         * @enum {string}
         */
        ApprovalAction: "approve" | "edit" | "reject";
        /** ApprovalOut */
        ApprovalOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ApprovalStatus"];
            action: components["schemas"]["ApprovalAction"] | null;
            /** Actor */
            actor: string | null;
            /** Decision Notes */
            decision_notes: string | null;
            /** Decided At */
            decided_at: string | null;
            /** Edit History */
            edit_history: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ApprovalQueueItem
         * @description One card in the approval queue: everything a reviewer needs in one call.
         */
        ApprovalQueueItem: {
            quote: components["schemas"]["QuoteOut"];
            job_request: components["schemas"]["JobRequestDetail"];
            customer: components["schemas"]["CustomerOut"] | null;
        };
        /**
         * ApprovalStatus
         * @enum {string}
         */
        ApprovalStatus: "pending" | "resolved";
        /** CatalogItemOut */
        CatalogItemOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Service Type */
            service_type: string;
            /** Unit */
            unit: string;
            /** Base Rate Cents */
            base_rate_cents: string;
            min_charge: components["schemas"]["Money"];
            /** Description */
            description: string;
            /** Labor Sensitive */
            labor_sensitive: boolean;
        };
        /** CatalogOut */
        CatalogOut: {
            /** Services */
            services: components["schemas"]["CatalogItemOut"][];
            /** Rules */
            rules: components["schemas"]["PricingRuleOut"][];
        };
        /**
         * CreateJobRequest
         * @description Ingest one inbound email.
         */
        CreateJobRequest: {
            /** Raw Source Text */
            raw_source_text: string;
            /** Subject */
            subject?: string | null;
            /** Sender Email */
            sender_email?: string | null;
            /** Received At */
            received_at?: string | null;
            /**
             * Run Now
             * @description Run the agent pipeline immediately after ingesting
             * @default true
             */
            run_now: boolean;
        };
        /** CustomerOut */
        CustomerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Contact Name */
            contact_name: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Status */
            status: string;
            /** Notes */
            notes: string | null;
            /** Addresses */
            addresses: components["schemas"]["AddressOut"][];
        };
        /** DashboardStats */
        DashboardStats: {
            /** Total Job Requests */
            total_job_requests: number;
            /** Pending Approval */
            pending_approval: number;
            /** Needs Review */
            needs_review: number;
            /** Routed To Human */
            routed_to_human: number;
            /** Sent */
            sent: number;
            /** Rejected */
            rejected: number;
            /** Total Spend Microcents */
            total_spend_microcents: number;
            /** Total Spend Display */
            total_spend_display: string;
            /** Mean Cost Per Run Microcents */
            mean_cost_per_run_microcents: number;
            /** Mean Cost Per Run Display */
            mean_cost_per_run_display: string;
        };
        /** DecisionIn */
        DecisionIn: {
            /** Actor */
            actor: string;
            /** Notes */
            notes?: string | null;
        };
        /** DraftMessageOut */
        DraftMessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Channel */
            channel: string;
            /** To Email */
            to_email: string | null;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Edited Subject */
            edited_subject: string | null;
            /** Edited Body */
            edited_body: string | null;
            /** Was Edited */
            was_edited: boolean;
        };
        /** EditQuoteIn */
        EditQuoteIn: {
            /** Line Items */
            line_items: components["schemas"]["LineItemEditIn"][];
            /** Actor */
            actor: string;
            /** Notes */
            notes?: string | null;
            /** Draft Subject */
            draft_subject?: string | null;
            /** Draft Body */
            draft_body?: string | null;
        };
        /** EvalCaseResultOut */
        EvalCaseResultOut: {
            /** Case Id */
            case_id: string;
            /** Tags */
            tags: string[];
            /** Passed */
            passed: boolean;
            /** Scores */
            scores: {
                [key: string]: unknown;
            };
            /** Diffs */
            diffs: {
                [key: string]: unknown;
            };
            /** Cost Microcents */
            cost_microcents: number;
            /** Latency Ms */
            latency_ms: number;
        };
        /** EvalRunDetail */
        EvalRunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Model */
            model: string;
            /** N Cases */
            n_cases: number;
            /** Subset */
            subset: string | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
            /** Passed */
            passed: boolean;
            /** Total Cost Microcents */
            total_cost_microcents: number;
            /** Cost Display */
            cost_display: string;
            /** Notes */
            notes: string | null;
            /** Results */
            results: components["schemas"]["EvalCaseResultOut"][];
        };
        /** EvalRunOut */
        EvalRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Model */
            model: string;
            /** N Cases */
            n_cases: number;
            /** Subset */
            subset: string | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
            /** Passed */
            passed: boolean;
            /** Total Cost Microcents */
            total_cost_microcents: number;
            /** Cost Display */
            cost_display: string;
            /** Notes */
            notes: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRequestDetail */
        JobRequestDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Subject */
            subject: string | null;
            /** Sender Email */
            sender_email: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            status: components["schemas"]["JobRequestStatus"];
            /** Needs Review */
            needs_review: boolean;
            /** Review Reasons */
            review_reasons: string[];
            /** Is New Customer */
            is_new_customer: boolean;
            /** Customer Id */
            customer_id: string | null;
            /** Customer Name */
            customer_name: string | null;
            /** Customer Match Score */
            customer_match_score: number | null;
            /** Routed Reason */
            routed_reason: string | null;
            /** Quote Id */
            quote_id: string | null;
            /** Quote Number */
            quote_number: string | null;
            quote_status: components["schemas"]["QuoteStatus"] | null;
            quote_total: components["schemas"]["Money"] | null;
            /** Latest Run Id */
            latest_run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Raw Source Text */
            raw_source_text: string;
            /** Parsed */
            parsed: {
                [key: string]: unknown;
            } | null;
            /** Field Confidence */
            field_confidence: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * JobRequestStatus
         * @enum {string}
         */
        JobRequestStatus: "received" | "processing" | "quoted" | "routed_to_human" | "failed";
        /** JobRequestSummary */
        JobRequestSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Subject */
            subject: string | null;
            /** Sender Email */
            sender_email: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            status: components["schemas"]["JobRequestStatus"];
            /** Needs Review */
            needs_review: boolean;
            /** Review Reasons */
            review_reasons: string[];
            /** Is New Customer */
            is_new_customer: boolean;
            /** Customer Id */
            customer_id: string | null;
            /** Customer Name */
            customer_name: string | null;
            /** Customer Match Score */
            customer_match_score: number | null;
            /** Routed Reason */
            routed_reason: string | null;
            /** Quote Id */
            quote_id: string | null;
            /** Quote Number */
            quote_number: string | null;
            quote_status: components["schemas"]["QuoteStatus"] | null;
            quote_total: components["schemas"]["Money"] | null;
            /** Latest Run Id */
            latest_run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LineItemEditIn */
        LineItemEditIn: {
            /** Catalog Code */
            catalog_code: string;
            /** Quantity */
            quantity: number | string;
            /** Trunk Diameter Band */
            trunk_diameter_band?: string | null;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** LineItemOut */
        LineItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** Catalog Code */
            catalog_code: string;
            /** Description */
            description: string;
            /** Quantity */
            quantity: string;
            /** Unit */
            unit: string;
            unit_price: components["schemas"]["Money"];
            base: components["schemas"]["Money"];
            subtotal: components["schemas"]["Money"];
            /** Applied Rules */
            applied_rules: components["schemas"]["AppliedRuleOut"][];
            /** Rationale */
            rationale: string;
            source: components["schemas"]["LineItemSource"];
        };
        /**
         * LineItemSource
         * @enum {string}
         */
        LineItemSource: "llm_proposed" | "human_edited";
        /**
         * Money
         * @description Cents plus its rendering. The frontend formats nothing itself.
         */
        Money: {
            /** Cents */
            cents: number;
            /** Display */
            display: string;
        };
        /** PricingRuleOut */
        PricingRuleOut: {
            /** Code */
            code: string;
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Applies To */
            applies_to: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Apply Order */
            apply_order: number;
        };
        /** QuoteOut */
        QuoteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Request Id
             * Format: uuid
             */
            job_request_id: string;
            /** Quote Number */
            quote_number: string;
            status: components["schemas"]["QuoteStatus"];
            line_subtotal: components["schemas"]["Money"];
            /** Adjustments */
            adjustments: components["schemas"]["AppliedRuleOut"][];
            adjusted_subtotal: components["schemas"]["Money"];
            tax: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
            /** Currency */
            currency: string;
            /** Pricing Context */
            pricing_context: {
                [key: string]: unknown;
            };
            /** Priced By Engine Version */
            priced_by_engine_version: string;
            /** Sent At */
            sent_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Line Items */
            line_items: components["schemas"]["LineItemOut"][];
            draft: components["schemas"]["DraftMessageOut"] | null;
            approval: components["schemas"]["ApprovalOut"] | null;
        };
        /**
         * QuoteStatus
         * @enum {string}
         */
        QuoteStatus: "draft" | "pending_approval" | "approved" | "rejected" | "sent";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "running" | "succeeded" | "routed_to_human" | "failed";
        /** SendResultOut */
        SendResultOut: {
            /**
             * Quote Id
             * Format: uuid
             */
            quote_id: string;
            /** Quote Number */
            quote_number: string;
            status: components["schemas"]["QuoteStatus"];
            /** To Email */
            to_email: string;
            /** Subject */
            subject: string;
            /** Provider Message Id */
            provider_message_id: string | null;
            /** Adapter */
            adapter: string;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
        };
        /**
         * StepStatus
         * @enum {string}
         */
        StepStatus: "ok" | "error";
        /** TraceStepOut */
        TraceStepOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Seq */
            seq: number;
            /** Tool Name */
            tool_name: string;
            /** Uses Llm */
            uses_llm: boolean;
            status: components["schemas"]["StepStatus"];
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            };
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Cost Microcents */
            cost_microcents: number;
            /** Cost Display */
            cost_display: string;
            /** Latency Ms */
            latency_ms: number;
            /** Cache Hit */
            cache_hit: boolean;
            /** Error */
            error: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_job_requests_api_job_requests_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobRequestStatus"] | null;
                needs_review?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRequestSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_request_api_job_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_request_api_job_requests__job_request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_pipeline_api_job_requests__job_request_id__rerun_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approval_queue_api_approvals_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalQueueItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_api_quotes__quote_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_quote_api_quotes__quote_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditQuoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_quote_api_quotes__quote_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_quote_api_quotes__quote_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_without_approval_api_quotes__quote_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    get_catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogOut"];
                };
            };
        };
    };
    list_customers_api_customers_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_runs_api_evals_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_eval_run_api_evals_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunDetail"];
                };
            };
        };
    };
    get_eval_run_api_evals__eval_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
