"""initial schema

Revision ID: 7d31fc378301
Revises: 
Create Date: 2026-09-22 15:14:04.771301

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7d31fc378301'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('existing', 'new', name='customer_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_from_job_request_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('eval_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('n_cases', sa.Integer(), nullable=False),
    sa.Column('subset', sa.String(length=80), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('total_cost_microcents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_runs'))
    )
    op.create_table('pricing_rules',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('applies_to', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('apply_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules')),
    sa.UniqueConstraint('code', name=op.f('uq_pricing_rules_code'))
    )
    op.create_table('service_catalog_items',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('base_rate_cents', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('min_charge_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('labor_sensitive', sa.Boolean(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_rate_cents > 0', name=op.f('ck_service_catalog_items_base_rate_positive')),
    sa.CheckConstraint('min_charge_cents > 0', name=op.f('ck_service_catalog_items_min_charge_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_catalog_items')),
    sa.UniqueConstraint('code', name=op.f('uq_service_catalog_items_code'))
    )
    op.create_table('addresses',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('line1', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('travel_zone', sa.String(length=20), nullable=False),
    sa.Column('property_notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_addresses_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index(op.f('ix_addresses_customer_id'), 'addresses', ['customer_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('eval_run_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diffs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_microcents', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], name=op.f('fk_eval_results_eval_run_id_eval_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_results'))
    )
    op.create_index(op.f('ix_eval_results_case_id'), 'eval_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_eval_results_eval_run_id'), 'eval_results', ['eval_run_id'], unique=False)
    op.create_table('job_requests',
    sa.Column('raw_source_text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('email', 'voicemail_transcript', name='job_request_source'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('is_new_customer', sa.Boolean(), nullable=False),
    sa.Column('customer_match_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.Enum('received', 'processing', 'quoted', 'routed_to_human', 'failed', name='job_request_status'), nullable=False),
    sa.Column('routed_reason', sa.Text(), nullable=True),
    sa.Column('fixture_case_id', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_job_requests_customer_id_customers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requests'))
    )
    op.create_index(op.f('ix_job_requests_customer_id'), 'job_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_job_requests_fixture_case_id'), 'job_requests', ['fixture_case_id'], unique=False)
    op.create_index(op.f('ix_job_requests_status'), 'job_requests', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('job_request_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('running', 'succeeded', 'routed_to_human', 'failed', name='run_status'), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_tokens_in', sa.Integer(), nullable=False),
    sa.Column('total_tokens_out', sa.Integer(), nullable=False),
    sa.Column('total_cached_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_microcents', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=60), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_request_id'], ['job_requests.id'], name=op.f('fk_agent_runs_job_request_id_job_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_job_request_id'), 'agent_runs', ['job_request_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('job_request_id', sa.Uuid(), nullable=False),
    sa.Column('quote_number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'sent', name='quote_status'), nullable=False),
    sa.Column('line_subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adjusted_subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pricing_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priced_by_engine_version', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('adjusted_subtotal_cents + tax_cents = total_cents', name=op.f('ck_quotes_total_reconciles')),
    sa.CheckConstraint('total_cents >= 0', name=op.f('ck_quotes_total_non_negative')),
    sa.ForeignKeyConstraint(['job_request_id'], ['job_requests.id'], name=op.f('fk_quotes_job_request_id_job_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes')),
    sa.UniqueConstraint('quote_number', name=op.f('uq_quotes_quote_number'))
    )
    op.create_index(op.f('ix_quotes_job_request_id'), 'quotes', ['job_request_id'], unique=False)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index('ix_quotes_status_created', 'quotes', ['status', 'created_at'], unique=False)
    op.create_table('approvals',
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'resolved', name='approval_status'), nullable=False),
    sa.Column('action', sa.Enum('approve', 'edit', 'reject', name='approval_action'), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('edited_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND action IS NULL AND decided_at IS NULL) OR (status = 'resolved' AND action IS NOT NULL AND decided_at IS NOT NULL)", name=op.f('ck_approvals_resolved_requires_action_and_time')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_approvals_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_quote_id'), 'approvals', ['quote_id'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_table('draft_messages',
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('edited_subject', sa.String(length=500), nullable=True),
    sa.Column('edited_body', sa.Text(), nullable=True),
    sa.Column('generated_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_run_id'], ['agent_runs.id'], name=op.f('fk_draft_messages_generated_by_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_draft_messages_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_messages'))
    )
    op.create_index(op.f('ix_draft_messages_quote_id'), 'draft_messages', ['quote_id'], unique=False)
    op.create_table('line_items',
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=True),
    sa.Column('catalog_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('base_cents', sa.Integer(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('applied_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trunk_diameter_band', sa.String(length=20), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('llm_proposed', 'human_edited', name='line_item_source'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_line_items_quantity_positive')),
    sa.CheckConstraint('subtotal_cents >= 0', name=op.f('ck_line_items_subtotal_non_negative')),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['service_catalog_items.id'], name=op.f('fk_line_items_catalog_item_id_service_catalog_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_line_items_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_items'))
    )
    op.create_index(op.f('ix_line_items_quote_id'), 'line_items', ['quote_id'], unique=False)
    op.create_table('trace_steps',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('uses_llm', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'error', name='step_status'), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_microcents', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_trace_steps_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trace_steps')),
    sa.UniqueConstraint('run_id', 'seq', name='uq_trace_steps_run_id_seq')
    )
    op.create_index(op.f('ix_trace_steps_run_id'), 'trace_steps', ['run_id'], unique=False)
    op.create_table('sent_messages',
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_sent_messages_approval_id_approvals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_sent_messages_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sent_messages'))
    )
    op.create_index(op.f('ix_sent_messages_approval_id'), 'sent_messages', ['approval_id'], unique=False)
    op.create_index(op.f('ix_sent_messages_quote_id'), 'sent_messages', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_messages_quote_id'), table_name='sent_messages')
    op.drop_index(op.f('ix_sent_messages_approval_id'), table_name='sent_messages')
    op.drop_table('sent_messages')
    op.drop_index(op.f('ix_trace_steps_run_id'), table_name='trace_steps')
    op.drop_table('trace_steps')
    op.drop_index(op.f('ix_line_items_quote_id'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_draft_messages_quote_id'), table_name='draft_messages')
    op.drop_table('draft_messages')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_quote_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_quotes_status_created', table_name='quotes')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_job_request_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_job_request_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_job_requests_status'), table_name='job_requests')
    op.drop_index(op.f('ix_job_requests_fixture_case_id'), table_name='job_requests')
    op.drop_index(op.f('ix_job_requests_customer_id'), table_name='job_requests')
    op.drop_table('job_requests')
    op.drop_index(op.f('ix_eval_results_eval_run_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_case_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_addresses_customer_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('service_catalog_items')
    op.drop_table('pricing_rules')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
